apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: 838107339577.dkr.ecr.ap-south-1.amazonaws.com/w-k-s/services-marketplace/auth-service:417
          env:
            - name: FUSIONAUTH_APPLICATION_ID
              valueFrom:
                secretKeyRef:
                  name: authservice.servicesmarketplace.w-k-s.io
                  key: FUSIONAUTH_APPLICATION_ID
            - name: FUSIONAUTH_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: authservice.servicesmarketplace.w-k-s.io
                  key: FUSIONAUTH_TENANT_ID
            - name: FUSIONAUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: authservice.servicesmarketplace.w-k-s.io
                  key: FUSIONAUTH_API_KEY
            - name: AUTHSERVICE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: authservice.servicesmarketplace.w-k-s.io
                  key: AUTHSERVICE_CLIENT_ID
            - name: AUTHSERVICE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: authservice.servicesmarketplace.w-k-s.io
                  key: AUTHSERVICE_CLIENT_SECRET
            - name: JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: authservice.servicesmarketplace.w-k-s.io
                  key: JDBC_URL
            - name: JDBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: authservice.servicesmarketplace.w-k-s.io
                  key: JDBC_USERNAME
            - name: JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authservice.servicesmarketplace.w-k-s.io
                  key: JDBC_PASSWORD
            - name: AMQP_URI
              valueFrom:
                secretKeyRef:
                  name: authservice.servicesmarketplace.w-k-s.io
                  key: AMQP_URI
            - name: FUSIONAUTH_SERVER_URL
              value: http://fusionauth
            - name: AUTH_SERVICE_HOST_URL
              value: "http://localhost:8082"
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "8082"
          ports:
            - containerPort: 8082
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8082
          #   initialDelaySeconds: 3
          #   periodSeconds: 3
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8082
          #   initialDelaySeconds: 3
          #   periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 80
      targetPort: 8082
  type: ClusterIP