apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: fusionauth
spec:
  selector:
    matchLabels:
      app: fusionauth
  template:
    metadata:
      labels:
        app: fusionauth
    spec:
      containers:
        - name: fusionauth
          image: fusionauth/fusionauth-app:1.24.0
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: fusionauth.servicesmarketplace.w-k-s.io
                  key: DATABASE_URL
            - name: DATABASE_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: fusionauth.servicesmarketplace.w-k-s.io
                  key: DATABASE_ROOT_USER
            - name: DATABASE_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fusionauth.servicesmarketplace.w-k-s.io
                  key: DATABASE_ROOT_PASSWORD
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: fusionauth.servicesmarketplace.w-k-s.io
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fusionauth.servicesmarketplace.w-k-s.io
                  key: DATABASE_PASSWORD
            - name: FUSIONAUTH_MEMORY
              value: 512M
            - name: FUSIONAUTH_SEARCH_ENGINE_TYPE
              value: database
          ports:
            - containerPort: 9011
          # This f***ing doesn't work
          # Readiness probe failed: Get http://172.31.56.94:9011/api/status: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
          # livenessProbe:
          #   httpGet:
          #     path: /api/status
          #     port: 9011
          #   initialDelaySeconds: 3
          #   periodSeconds: 3
          # readinessProbe:
          #   httpGet:
          #     path: /api/status
          #     port: 9011
          #   initialDelaySeconds: 3
          #   periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: fusionauth
spec:
  selector:
    app: fusionauth
  ports:
    - port: 80
      targetPort: 9011
  type: LoadBalancer