apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: order-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: 838107339577.dkr.ecr.ap-south-1.amazonaws.com/w-k-s/services-marketplace/order-service:37b0549e29fee3ef3eb0a1d7b334e1e80f34f95b
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: order-service.servicesmarketplace.w-k-s.io
                  key: JDBC_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: order-service.servicesmarketplace.w-k-s.io
                  key: JDBC_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-service.servicesmarketplace.w-k-s.io
                  key: JDBC_PASSWORD
            - name: SPRING_RABBITMQ_ADDRESSES
              valueFrom:
                secretKeyRef:
                  name: order-service.servicesmarketplace.w-k-s.io
                  key: AMQP_URI
          ports:
            - containerPort: 8083
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 80
      targetPort: 8083
  type: ClusterIP