version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    environment:
      DATABASE_URL: jdbc:postgresql://host.docker.internal:5432/fusionauth
      DATABASE_ROOT_USER: postgres
      DATABASE_ROOT_PASSWORD: 7713659
      DATABASE_USER: fusionauth
      DATABASE_PASSWORD: password
      FUSIONAUTH_MEMORY: 512M
      FUSIONAUTH_SEARCH_ENGINE_TYPE: database
    restart: unless-stopped
    ports:
      - 9011:9011

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: wkas/sm-auth-service
    restart: always
    env_file:
      - docker-infra/auth-service.env
    environment:
      clientId: auth-service
      clientSecret: Password@1
      fusionServerUrl: http://fusionauth:9011
      fusionApplicationId: d64656ea-4f62-4127-b312-91afeeca96f9
      fusionTenantId: a84b174a-965c-44fe-807d-623efc3bff9c
      fusionApiKey: 9Am1DMurFnQo6B_Zae3qLdSqd2mOk7w4APyPoCTnLHw
      authServiceBaseUrl: http://localhost:8082
      serverHost: http://0.0.0.0
      serverPort: 8082
      amqpUri: amqp://rabbitmq:5672
      jdbcUrl: jdbc:postgresql://docker.for.mac.host.internal:5432/auth
      jdbcUsername: waqqassheikh
      jdbcPassword: 7713659
    ports:
      - 8082:8082

  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    image: wkas/sm-customer-service
    restart: always
    ports:
      - 8081:8081
    environment:
      clientId: customer-service
      clientSecret: Password@1
      jdbcUrl: jdbc:postgresql://docker.for.mac.host.internal:5432/customer
      jdbcUsername: waqqassheikh
      jdbcPassword: 7713659
      amqpHost: rabbitmq
      amqpPort: 5672
      serverHost: http://0.0.0.0
      serverPort: 8081
      authServiceBaseUrl: http://auth-service:8082

  service-provider-service:
    build:
      context: ./service-provider-service
      dockerfile: Dockerfile
    image: wkas/sm-sp-service
    restart: always
    environment:
      clientId: service-provider-service
      clientSecret: Password@1
      jdbcUrl: jdbc:postgresql://docker.for.mac.host.internal:5432/provider
      jdbcUsername: waqqassheikh
      jdbcPassword: 7713659
      amqpHost: rabbitmq
      amqpPort: 5672
      serverHost: http://0.0.0.0
      serverPort: 8084
      authServiceBaseUrl: http://auth-service:8082
    ports:
      - 8084:8084

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    image: wkas/sm-order-service
    restart: always
    ports:
      - 8083:8083
    environment:
      SERVER_PORT: 8083
      SPRING_DATASOURCE_URL: jdbc:postgresql://docker.for.mac.host.internal:5432/service_order
      SPRING_DATASOURCE_USERNAME: waqqassheikh
      SPRING_DATASOURCE_PASSWORD: 7713659
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: wkas/sm-api-gateway
    restart: always
    ports:
      - 8080:8080
    environment:
      SERVER_PORT: 8080
      APPLICATION_HOSTS_CUSTOMER_SERVICE: http://customer-service:8081
      APPLICATION_HOSTS_AUTH_SERVICE: http://auth-service:8082
      APPLICATION_HOSTS_ORDER_SERVICE: http://order-service:8083
      APPLICATION_HOSTS_SERVICE_PROVIDER_SERVICE: http://service-provider-service:8084
