version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  keycloak:
    image: jboss/keycloak
    ports:
      - 8180:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: host.docker.internal
      DB_PORT: 5432
      DB_USER: keycloak
      DB_PASSWORD: password
      DB_DATABASE: keycloak

