version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    environment:
      DATABASE_URL: jdbc:postgresql://host.docker.internal:5432/fusionauth
      DATABASE_ROOT_USER: postgres
      DATABASE_ROOT_PASSWORD: 7713659
      DATABASE_USER: fusionauth
      DATABASE_PASSWORD: password
      FUSIONAUTH_MEMORY: 512M
      FUSIONAUTH_SEARCH_ENGINE_TYPE: database
    restart: unless-stopped
    ports:
      - 9011:9011

  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    volumes:
      - ./docker-infra/axonserver/data:/data
      - ./docker-infra/axonserver/events:/eventdata
      - ./docker-infra/axonserver/config:/config:ro
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: wkas/sm-auth-service
    restart: always
    environment:
      fusionServerUrl: http://fusionauth:9011
      fusionApplicationId: d64656ea-4f62-4127-b312-91afeeca96f9
      fusionTenantId: a84b174a-965c-44fe-807d-623efc3bff9c
      fusionApiKey: 9Am1DMurFnQo6B_Zae3qLdSqd2mOk7w4APyPoCTnLHw
      serverHost: http://0.0.0.0
      serverPort: 8082
      amqpHost: rabbitmq
      amqpPort: 5672
    ports:
      - 8082:8082
    entrypoint: ["./wait-for-it.sh", "fusionauth:9011","-t","0","--strict","--","java","-jar","/app.jar"]

  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    image: wkas/sm-customer-service
    restart: always
    environment:
      jdbcUrl: jdbc:postgresql://docker.for.mac.host.internal:5432/customer
      jdbcUsername: waqqassheikh
      jdbcPassword: 7713659
      amqpHost: rabbitmq
      amqpPort: 5672
      serverHost: http://0.0.0.0
      serverPort: 8081
    entrypoint: ["./wait-for-it.sh", "rabbitmq:5672","-t","0","--strict","--","java","-jar","/app.jar"]

  job-service:
    build:
      context: ./job-service
      dockerfile: Dockerfile
    image: wkas/sm-job-service
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://docker.for.mac.host.internal:5432/service_order_query
      SPRING_DATASOURCE_USERNAME: waqqassheikh
      SPRING_DATASOURCE_PASSWORD: 7713659
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      AXON_AXONSERVER_SERVERS: axonserver:8124
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/auth
    entrypoint: ["./wait-for-it.sh", "keycloak:8080","-t","0","--strict","--","java","-jar","/app.jar"]