apiVersion: v1
kind: Service
metadata:
  name: axonserver-gui
  labels:
    app: axonserver-gui
spec:
  ports:
    - name: gui
      port: 8024
      targetPort: 8024
      nodePort: 30824
  selector:
    app: axonserver
  type: NodePort
