apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:11.5
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
            - mountPath: /docker-entrypoint-initdb.d
              name: psql-initdb

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: psql-initdb
          configMap:
            name: psql-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: psql-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE keycloak;

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: jboss/keycloak:11.0.2
          env:
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: DB_VENDOR
              value: postgres
            - name: DB_ADDR
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_DATABASE
              value: keycloak
            - name: JAVA_OPTS #https://keycloak.discourse.group/t/cant-import-realm-using-docker-image/259/14
              value: |
                -Dkeycloak.profile.feature.scripts=enabled
                -Dkeycloak.profile.feature.upload_scripts=enabled -server -Xms64m -Xmx512m 
                -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true 
                -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /tmp
              name: keycloak-data
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-pvc
