apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: axonserver
  labels:
    app: axonserver
spec:
  serviceName: axonserver
  replicas: 2
  selector:
    matchLabels:
      app: axonserver
  template:
    metadata:
      labels:
        app: axonserver
    spec:
      containers:
        - name: axonserver
          image: axoniq/axonserver
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 8124
              protocol: TCP
            - name: gui
              containerPort: 8024
              protocol: TCP
          volumeMounts:
            - name: eventstore
              mountPath: /eventdata
            - name: data
              mountPath: /data
          readinessProbe:
            httpGet:
              port: 8024
              path: /actuator/info
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
  volumeClaimTemplates:
    - metadata:
        name: eventstore
      spec:
        storageClassName: axon-eventstore
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: data
      spec:
        storageClassName: axon-data
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---

