name: Deploy
on:
  workflow_dispatch:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: dev
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      
      DB_INSTANCE_URL: ${{ secrets.DB_INSTANCE_URL }} # should not end with '/'
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }} 
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD}}
      
      HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}

      FUSIONAUTH_URL: ${{ secrets.FUSIONAUTH_URL }}
      FUSIONAUTH_APPLICATION_ID: ${{ secrets.FUSIONAUTH_APPLICATION_ID }}
      FUSIONAUTH_TENANT_ID: ${{ secrets.FUSIONAUTH_TENANT_ID }}
      FUSIONAUTH_API_KEY: ${{ secrets.FUSIONAUTH_API_KEY }}
  
      TF_VAR_notification_email: ${{ secrets.NOTIFICATION_EMAIL }}
      TF_VAR_cloudamqp_customer_api_key: ${{ secrets.CLOUD_AMQP_CUSTOMER_API_KEY }}
      TF_VAR_cloudamqp_region: ${{ secrets.CLOUD_AMQP_REGION }}
      TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_vpc_id: ${{ secrets.VPC_ID }}
      TF_VAR_private_subnet_ids : ${{ secrets.PRIVATE_SUBNET_IDS }}
      TF_VAR_public_subnet_ids : ${{ secrets.PUBLIC_SUBNET_IDS }}
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.0
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Configure Kubectl
        # TODO: Get cluster_name from terraform output
        run: |
          aws eks --region "$AWS_DEFAULT_REGION" update-kubeconfig --name $(terraform output cluster_name)

      - name: Deploy Kubernetes Dashboard
        run: |
          wget -O v0.3.6.tar.gz https://codeload.github.com/kubernetes-sigs/metrics-server/tar.gz/v0.3.6 && tar -xzf v0.3.6.tar.gz
          kubectl apply -f metrics-server-0.3.6/deploy/1.8+/
          echo "Maybe later setup a Kubernetes dashboard: https://learn.hashicorp.com/tutorials/terraform/eks"

      - name: Create Kubernetes secrets (deprecated)
        run: |
          kubectl create ns app;

          kubectl -n app create secret generic fusionauth.servicesmarketplace.w-k-s.io \
          --from-literal=DATABASE_URL="$DB_INSTANCE_URL/fusionauth" \
          --from-literal=DATABASE_ROOT_USER="$DATABASE_USERNAME" \
          --from-literal=DATABASE_ROOT_PASSWORD="$DATABASE_PASSWORD" \
          --from-literal=DATABASE_USER="$DATABASE_USERNAME" \
          --from-literal=DATABASE_PASSWORD="$DATABASE_PASSWORD";

          kubectl -n app create secret generic auth-service.servicesmarketplace.w-k-s.io \
          --from-literal=FUSIONAUTH_APPLICATION_ID="$FUSIONAUTH_APPLICATION_ID" \
          --from-literal=FUSIONAUTH_TENANT_ID="$FUSIONAUTH_TENANT_ID" \
          --from-literal=FUSIONAUTH_API_KEY="$FUSIONAUTH_API_KEY" \
          --from-literal=AUTHSERVICE_CLIENT_ID="$AUTHSERVICE_CLIENT_ID" \
          --from-literal=AUTHSERVICE_CLIENT_SECRET="$AUTHSERVICE_CLIENT_SECRET" \
          --from-literal=JDBC_URL="$DB_INSTANCE_URL/sm-auth?currentSchema=public&user=$DATABASE_USERNAME&password=$DATABASE_PASSWORD" \
          --from-literal=JDBC_USERNAME="$DATABASE_USERNAME" \
          --from-literal=JDBC_PASSWORD="$DATABASE_PASSWORD" \
          --from-literal=AMQP_URI="$(terraform output cloudamqp_url)";

          kubectl -n app create secret generic order-service.servicesmarketplace.w-k-s.io \
          --from-literal=JDBC_URL="$DB_INSTANCE_URL/sm-orders" \
          --from-literal=JDBC_USERNAME="$DATABASE_USERNAME" \
          --from-literal=JDBC_PASSWORD="$DATABASE_PASSWORD" \
          --from-literal=AMQP_URI="$(terraform output cloudamqp_url)";

          kubectl -n app create secret generic customer-service.servicesmarketplace.w-k-s.io \
          --from-literal=JDBC_URL="$DB_INSTANCE_URL/sm-customers?currentSchema=public&user=$DATABASE_USERNAME&password=$DATABASE_PASSWORD" \
          --from-literal=JDBC_USERNAME="$DATABASE_USERNAME" \
          --from-literal=JDBC_PASSWORD="$DATABASE_PASSWORD" \
          --from-literal=AMQP_URI="$(terraform output cloudamqp_url)";

          kubectl -n app create secret generic service-provider-service.servicesmarketplace.w-k-s.io \
          --from-literal=JDBC_URL="$DB_INSTANCE_URL/sm-providers?currentSchema=public&user=$DATABASE_USERNAME&password=$DATABASE_PASSWORD" \
          --from-literal=JDBC_USERNAME="$DATABASE_USERNAME" \
          --from-literal=JDBC_PASSWORD="$DATABASE_PASSWORD" \
          --from-literal=AMQP_URI="$(terraform output cloudamqp_url)";

      - name: Deploy Application
        working-directory: ./kubernetes-infra/app
        run: |
          kubectl apply -f .